name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout  code
      - name: Checkout code
        uses: actions/checkout@v3

      #configur JDk
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # build the App
      - name: Build with Maven
        run: mvn clean install
